#Jekyll 
permalink: /:title
plugins: [jekyll-paginate-v2]
encoding: "utf-8"

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded
exclude: ["Gemfile", "Gemfile.lock", "vendor"]

excerpt_separator: <!--e-->

pagination:
  enabled: true
  per_page: 8
  permalink: "/page=:num/"
  sort_reverse: true
# sort_field: "order"

sitemap_exclude: ["assets/"]

#Site
url: https://do-your-own-seo.com
lang: uk
languages: "uk ru en"
name: "Homemade SEO"

author:
  name: Olya Vo
  job: Technical SEO
  thumb: /images/author-avatar.jpg
  github: https://github.com/do-your-own-seo?tab=repositories
  twitter: https://twitter.com/do_your_own_seo
  email: mailto:7d1ga77zj@mozmail.com

ga: UA-145849621-1
comments: true

github-repo: "do-your-own-seo/do-your-own-seo.github.io"
staticman:
    branch: "source"
    app: "https://dyos.fly.dev"
